<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHf42a5A\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHf42a5A/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHf42a5A.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHf42a5A\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHf42a5A\appAppKernelProdContainer([
    'container.build_hash' => 'Hf42a5A',
    'container.build_id' => 'dbfe72a8',
    'container.build_time' => 1698240204,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHf42a5A');
