<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Pb9aS7\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Pb9aS7/appAppKernelProdContainer.php') {
    touch(__DIR__.'/Container7Pb9aS7.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\Container7Pb9aS7\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \Container7Pb9aS7\appAppKernelProdContainer([
    'container.build_hash' => '7Pb9aS7',
    'container.build_id' => 'd4cb1b4a',
    'container.build_time' => 1698314655,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Pb9aS7');
